url=http://82.197.92.72:8080/patient/login
adminUrl=http://82.197.92.72:8080/admin/login
puname=Alex@A
ppword=Alex@A
adminurl=http://82.197.92.72:8080/admin/login
adminuname=admin1
adminpword=admin123
